### ISSUE TITLE
有测试视频跟demo吗？windows可以运行不？

### ISSUE THREAD

**Issue by jaccen** [15850864092/StitchVideo#1]
百度云
链接：https://pan.baidu.com/s/1nWki4v9PYMRXC9PMZm8wlA?pwd=jz4z 
提取码：jz4z

**Comment by 15850864092** [comment]
v1分支里面有测试图片，测试视频比较大没有上传，v1.1分支里面没有上传数据和畸变、拼接参数需要自己根据情况生成，用到的工具都上传了。windows下没有试过，推荐还是在Linux下运行，需要配置挺多环境的，opencv编译时很多选项得打开。
